# Generated by Django 4.0.6 on 2022-07-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_status_delete_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='user',
            new_name='owner',
        ),
    ]
