# Generated by Django 4.0.6 on 2022-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_user_note_owner_rename_user_status_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_choices',
            field=models.CharField(choices=[('Read', 'Read'), ('Reading', 'Reading'), ('Want to Read', 'Want to Read')], default='Want to Read', max_length=20),
        ),
    ]
